# Site settings
title: Riverside over the Ocean
subtitle: by Ian Park
email: vreality64@gmail.com
description: 개인 블로그 입 니다 :)
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
author: Seonghyeon Park
city: Seoul
country: Republic of Korea
phone: (+82)10 0000-0000

# Social settings
github_url: https://www.github.com/vreality64
linkedin_url: https://www.linkedin.com/in/vreality64

# Build settings
markdown: kramdown
