# Site settings
title: Riverside over the Ocean
subtitle: '| Ian Park'
email: vreality64@gmail.com
description: 개인 블로그 입니다 :)
base_url: /blog # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site
author: Seonghyeon Park
city: Seoul
country: Republic of Korea

# Social settings
github_url: https://www.github.com/vreality64
linkedin_url: https://www.linkedin.com/in/vreality64

# Build settings
markdown: kramdown
# paginate: 5
# paginate_path: "/blog/post/page:num/"

defaults:
  -
    scope:
      path: ""
      type: "demo"
    values:
      layout: "page"
      author: "Ian Park"

collections:
  blog:
    output: true
    permalink: /:collection/post/:name
  demo:
    output: true
    permalink: /:collection/:name

  # posts:
  #  output: true
